package com.example.ui.localization

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // App & Navigation
    val appName: String,
    val appTitle: String = appName,
    val navHome: String,
    val homeTab: String = navHome,
    val navQuran: String,
    val quranTab: String = navQuran,
    val navQibla: String,
    val qiblaTab: String = navQibla,
    val navAzkar: String,
    val azkarTab: String = navAzkar,
    val navSettings: String,
    val settingsTab: String = navSettings,
    val athanSound: String = "صوت الأذان",
    val theme: String = "المظهر",

    // Prayer Times
    val nextPrayer: String,
    val remainingTime: String,
    val fajr: String,
    val sunrise: String,
    val dhuhr: String,
    val asr: String,
    val maghrib: String,
    val isha: String,
    val todayPrayers: String,
    val hijriDate: String,
    val gregorianDate: String,
    val location: String,
    val changeLocation: String,
    val autoGps: String,
    val searchingLocation: String,
    val permissionRequired: String,
    val grantGps: String,
    val manualCity: String,
    val prayerAlertMode: String,
    val fullAthan: String,
    val takbeerOnly: String,
    val tone: String,
    val silent: String,
    val playAthanTest: String,
    val stopAthan: String,

    // Qibla Compass
    val qiblaTitle: String,
    val pointToKaaba: String,
    val qiblaAligned: String,
    val degreesFromNorth: String,
    val distanceToKaaba: String,
    val calibrateCompass: String,
    val compassHint: String,

    // Quran
    val quranTitle: String,
    val searchSurah: String,
    val surahs: String,
    val juz: String,
    val bookmarks: String,
    val versesCount: String,
    val meccan: String,
    val medinan: String,
    val fontSize: String,
    val reciter: String,
    val nowPlaying: String,
    val playAllSurah: String,
    val pauseAudio: String,
    val resumeAudio: String,
    val nextAyah: String,
    val prevAyah: String,
    val bismillah: String,
    val noBookmarks: String,
    val bookmarkAdded: String,
    val bookmarkRemoved: String,

    // Azkar & Tasbeeh
    val azkarTitle: String,
    val morningAzkar: String,
    val eveningAzkar: String,
    val postPrayerAzkar: String,
    val sleepAzkar: String,
    val tasbeehCounter: String,
    val resetCounter: String,
    val target: String,
    val totalDone: String,
    val tapToCount: String,
    val subhanallah: String,
    val alhamdulillah: String,
    val allahuAkbar: String,
    val lailahaillallah: String,
    val astaghfirullah: String,

    // Settings
    val settingsTitle: String,
    val language: String,
    val selectLanguage: String,
    val calculationMethod: String,
    val muezzinVoice: String,
    val notifications: String,
    val notificationsDesc: String,
    val darkMode: String,
    val followSystem: String,
    val aboutApp: String,
    val version: String,
    val themeColor: String = "ألوان المظهر والتصميم",
    val selectThemeColor: String = "اختر لون السمة المفضلة",
    val backgroundStyleTitle: String = "شكل وخلفية التطبيق",
    val selectBackgroundStyle: String = "اختر نمط وخلفية الشاشة",
    val islamic3dTitle: String = "الواجهة الإسلامية ثلاثية الأبعاد 3D",
    val islamic3dSubtitle: String = "استمتع بمشاهد إسلامية مجسمة وعالية الدقة",
    val customizeAppName: String = "تغيير اسم التطبيق",
    val changeAppNameTitle: String = "تخصيص اسم التطبيق",
    val enterAppNameHint: String = "اكتب اسم التطبيق الجديد...",
    val save: String = "حفظ",
    val cancel: String = "إلغاء",
    val publishToStore: String = "دليل رفع ونشر التطبيق على المتاجر",
    val publishToStoreDesc: String = "خطوات تصدير APK / AAB والنشر على Google Play و App Store",
    val quickPresets: String = "نماذج أسماء مقترحة"
)

val LocalAppStrings = compositionLocalOf { getStringsForLanguage(AppLanguage.ENGLISH) }

fun getAppStrings(lang: AppLanguage): AppStrings = getStringsForLanguage(lang)

fun getStringsForLanguage(lang: AppLanguage): AppStrings {
    return when (lang) {
        AppLanguage.ARABIC -> AppStrings(
            appName = "نور الإيمان",
            navHome = "الصلاة",
            navQuran = "القرآن",
            navQibla = "القبلة",
            navAzkar = "الأذكار والسبحة",
            navSettings = "الإعدادات",
            nextPrayer = "الصلاة القادمة",
            remainingTime = "متبقي",
            fajr = "الفجر",
            sunrise = "الشروق",
            dhuhr = "الظهر",
            asr = "العصر",
            maghrib = "المغرب",
            isha = "العشاء",
            todayPrayers = "مواقيت صلاة اليوم",
            hijriDate = "التاريخ الهجري",
            gregorianDate = "التاريخ الميلادي",
            location = "الموقع الحالي",
            changeLocation = "تغيير المدينة",
            autoGps = "تحديد تلقائي عبر GPS",
            searchingLocation = "جاري تحديد الموقع...",
            permissionRequired = "يحتاج التطبيق إذن الموقع لحساب أوقات الصلاة والقبلة بدقة",
            grantGps = "تفعيل الموقع",
            manualCity = "اختيار مدينة يدوياً",
            prayerAlertMode = "وضع تنبيه الصلاة",
            fullAthan = "أذان كامل",
            takbeerOnly = "تكبير فقط",
            tone = "نغمة هادئة",
            silent = "صامت",
            playAthanTest = "تجربة الأذان",
            stopAthan = "إيقاف الأذان",
            qiblaTitle = "بوصلة القبلة",
            pointToKaaba = "وجّه هاتفك نحو الكعبة المشرفة",
            qiblaAligned = "أنت الآن باتجاه القبلة مباشرة",
            degreesFromNorth = "الدرجة من الشمال",
            distanceToKaaba = "المسافة إلى مكة المكرمة",
            calibrateCompass = "يرجى تحريك الهاتف على شكل رقم 8 للمعايرة",
            compassHint = "ضع الهاتف بشكل مستوٍ للحصول على أدق قراءة",
            quranTitle = "القرآن الكريم",
            searchSurah = "ابحث عن سورة أو آية...",
            surahs = "السور",
            juz = "الأجزاء",
            bookmarks = "المحفوظات",
            versesCount = "آياتها",
            meccan = "مكية",
            medinan = "مدنية",
            fontSize = "حجم الخط",
            reciter = "القارئ",
            nowPlaying = "يتم الاستماع الآن",
            playAllSurah = "تشغيل السورة",
            pauseAudio = "إيقاف مؤقت",
            resumeAudio = "استئناف",
            nextAyah = "الآية التالية",
            prevAyah = "الآية السابقة",
            bismillah = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
            noBookmarks = "لا توجد آيات محفوظة بعد",
            bookmarkAdded = "تمت إضافة الآية للمحفوظات",
            bookmarkRemoved = "تمت إزالة الآية من المحفوظات",
            azkarTitle = "الأذكار والسبحة الإلكترونية",
            morningAzkar = "أذكار الصباح",
            eveningAzkar = "أذكار المساء",
            postPrayerAzkar = "أذكار بعد الصلاة",
            sleepAzkar = "أذكار النوم",
            tasbeehCounter = "السبحة الإلكترونية",
            resetCounter = "تصفير العداد",
            target = "الهدف",
            totalDone = "المجموع الكلي",
            tapToCount = "المس الشاشة للتسبيح",
            subhanallah = "سُبْحَانَ اللَّهِ",
            alhamdulillah = "الْحَمْدُ لِلَّهِ",
            allahuAkbar = "اللَّهُ أَكْبَرُ",
            lailahaillallah = "لَا إِلَٰهَ إِلَّا اللَّهُ",
            astaghfirullah = "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ",
            settingsTitle = "الإعدادات العامة",
            language = "لغة التطبيق",
            selectLanguage = "اختر اللغة المفضلة",
            calculationMethod = "طريقة حساب المواقيت",
            muezzinVoice = "صوت المؤذن",
            notifications = "إشعارات الأذان",
            notificationsDesc = "تنبيهات فورية عند دخول وقت كل صلاة",
            darkMode = "المظهر الداكن",
            followSystem = "تلقائي حسب النظام",
            aboutApp = "عن تطبيق نور الإيمان",
            version = "الإصدار 1.0"
        )
        AppLanguage.URDU -> AppStrings(
            appName = "نور الایمان",
            navHome = "نماز",
            navQuran = "قرآن",
            navQibla = "قبلہ",
            navAzkar = "اذکار و تسبیح",
            navSettings = "ترتیبات",
            nextPrayer = "اگلی نماز",
            remainingTime = "باقی وقت",
            fajr = "فجر",
            sunrise = "طلوع آفتاب",
            dhuhr = "ظہر",
            asr = "عصر",
            maghrib = "مغرب",
            isha = "عشاء",
            todayPrayers = "آج کے نماز کے اوقات",
            hijriDate = "ہجری تاریخ",
            gregorianDate = "عیسوی تاریخ",
            location = "موجودہ مقام",
            changeLocation = "شہر تبدیل کریں",
            autoGps = "خودکار GPS",
            searchingLocation = "مقام تلاش کیا جا رہا ہے...",
            permissionRequired = "نماز اور قبلہ کے درست حساب کے لیے مقام کی اجازت درکار ہے",
            grantGps = "مقام فعال کریں",
            manualCity = "شہر منتخب کریں",
            prayerAlertMode = "نماز الرٹ موڈ",
            fullAthan = "مکمل اذان",
            takbeerOnly = "صرف تکبیر",
            tone = "نرم ٹون",
            silent = "خاموش",
            playAthanTest = "اذان سنیں",
            stopAthan = "اذان روکیں",
            qiblaTitle = "قبلہ رخ",
            pointToKaaba = "اپنا فون کعبہ کی طرف رکھیں",
            qiblaAligned = "آپ قبلہ رخ ہیں",
            degreesFromNorth = "شمال سے ڈگری",
            distanceToKaaba = "مکہ تک فاصلہ",
            calibrateCompass = "درستگی کے لیے فون کو 8 کی شکل میں گھمائیں",
            compassHint = "درست سمت کے لیے فون کو سیدھا رکھیں",
            quranTitle = "قرآن مجید",
            searchSurah = "سورت یا آیت تلاش کریں...",
            surahs = "سورتیں",
            juz = "پارے",
            bookmarks = "محفوظ شدہ",
            versesCount = "آیات",
            meccan = "مکی",
            medinan = "مدنی",
            fontSize = "فونٹ سائز",
            reciter = "قاری",
            nowPlaying = "تلاوت جاری ہے",
            playAllSurah = "سورت چلائیں",
            pauseAudio = "روکیں",
            resumeAudio = "دوبارہ چلائیں",
            nextAyah = "اگلی آیت",
            prevAyah = "پچھلی آیت",
            bismillah = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
            noBookmarks = "کوئی محفوظ شدہ آیت نہیں",
            bookmarkAdded = "آیت محفوظ کر لی گئی",
            bookmarkRemoved = "آیت ہٹا دی گئی",
            azkarTitle = "اذکار اور تسبیح",
            morningAzkar = "صبح کے اذکار",
            eveningAzkar = "شام کے اذکار",
            postPrayerAzkar = "نماز کے بعد اذکار",
            sleepAzkar = "سونے کے اذکار",
            tasbeehCounter = "ڈیجیٹل تسبیح",
            resetCounter = "ری سیٹ کریں",
            target = "ہدف",
            totalDone = "کل تعداد",
            tapToCount = "گننے کے لیے اسکرین کو چھوئیں",
            subhanallah = "سُبْحَانَ اللَّهِ",
            alhamdulillah = "الْحَمْدُ لِلَّهِ",
            allahuAkbar = "اللَّهُ أَكْبَرُ",
            lailahaillallah = "لَا إِلَٰهَ إِلَّا اللَّهُ",
            astaghfirullah = "أَسْتَغْفِرُ اللَّهَ",
            settingsTitle = "ترتیبات",
            language = "زبان",
            selectLanguage = "زبان منتخب کریں",
            calculationMethod = "حساب کا طریقہ",
            muezzinVoice = "مؤذن کی آواز",
            notifications = "اذان نوٹیفکیشن",
            notificationsDesc = "نماز کے وقت بروقت الرٹ",
            darkMode = "ڈارک موڈ",
            followSystem = "سسٹم کے مطابق",
            aboutApp = "ایپ کے بارے میں",
            version = "ورژن 1.0"
        )
        AppLanguage.FRENCH -> AppStrings(
            appName = "Noor Al-Iman",
            navHome = "Prières",
            navQuran = "Coran",
            navQibla = "Qibla",
            navAzkar = "Azkar",
            navSettings = "Paramètres",
            nextPrayer = "Prochaine Prière",
            remainingTime = "Temps restant",
            fajr = "Fajr",
            sunrise = "Chourouq",
            dhuhr = "Dhuhr",
            asr = "Asr",
            maghrib = "Maghrib",
            isha = "Isha",
            todayPrayers = "Horaires de prière du jour",
            hijriDate = "Date Hégirienne",
            gregorianDate = "Date Grégorienne",
            location = "Position actuelle",
            changeLocation = "Changer de ville",
            autoGps = "Localisation GPS automatique",
            searchingLocation = "Recherche de position...",
            permissionRequired = "Autorisation de localisation requise",
            grantGps = "Activer GPS",
            manualCity = "Choisir une ville",
            prayerAlertMode = "Mode d'alerte",
            fullAthan = "Adhan complet",
            takbeerOnly = "Takbeer seul",
            tone = "Tonalité douce",
            silent = "Silencieux",
            playAthanTest = "Tester l'Adhan",
            stopAthan = "Arrêter l'Adhan",
            qiblaTitle = "Boussole Qibla",
            pointToKaaba = "Dirigez votre téléphone vers la Kaaba",
            qiblaAligned = "Vous êtes face à la Qibla",
            degreesFromNorth = "Degrés depuis le Nord",
            distanceToKaaba = "Distance jusqu'à La Mecque",
            calibrateCompass = "Calibrez en dessinant un 8 avec le téléphone",
            compassHint = "Tenez l'appareil à plat pour plus de précision",
            quranTitle = "Saint Coran",
            searchSurah = "Rechercher une sourate ou un verset...",
            surahs = "Sourates",
            juz = "Juz",
            bookmarks = "Favoris",
            versesCount = "versets",
            meccan = "Mecquoise",
            medinan = "Médinoise",
            fontSize = "Taille du texte",
            reciter = "Récitateur",
            nowPlaying = "En cours d'écoute",
            playAllSurah = "Écouter la sourate",
            pauseAudio = "Pause",
            resumeAudio = "Reprendre",
            nextAyah = "Verset suivant",
            prevAyah = "Verset précédent",
            bismillah = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
            noBookmarks = "Aucun verset enregistré",
            bookmarkAdded = "Verset ajouté aux favoris",
            bookmarkRemoved = "Verset retiré des favoris",
            azkarTitle = "Invocations & Tasbih",
            morningAzkar = "Invocations du Matin",
            eveningAzkar = "Invocations du Soir",
            postPrayerAzkar = "Après la Prière",
            sleepAzkar = "Avant de Dormir",
            tasbeehCounter = "Chapelet Électronique (Tasbih)",
            resetCounter = "Réinitialiser",
            target = "Objectif",
            totalDone = "Total réalisé",
            tapToCount = "Touchez l'écran pour compter",
            subhanallah = "Subhanallah (Gloire à Dieu)",
            alhamdulillah = "Alhamdulillah (Louange à Dieu)",
            allahuAkbar = "Allahu Akbar (Dieu est le plus grand)",
            lailahaillallah = "La ilaha illa Allah",
            astaghfirullah = "Astaghfirullah (Pardon à Dieu)",
            settingsTitle = "Paramètres",
            language = "Langue de l'application",
            selectLanguage = "Choisir la langue",
            calculationMethod = "Méthode de calcul",
            muezzinVoice = "Voix du Muezzin",
            notifications = "Notifications Adhan",
            notificationsDesc = "Rappels sonores à chaque prière",
            darkMode = "Mode Sombre",
            followSystem = "Selon le système",
            aboutApp = "À propos de Noor Al-Iman",
            version = "Version 1.0"
        )
        AppLanguage.SPANISH -> AppStrings(
            appName = "Noor Al-Iman",
            navHome = "Oraciones",
            navQuran = "Corán",
            navQibla = "Alquibla",
            navAzkar = "Azkar",
            navSettings = "Ajustes",
            nextPrayer = "Próxima Oración",
            remainingTime = "Tiempo restante",
            fajr = "Fajr",
            sunrise = "Amanecer",
            dhuhr = "Dhuhr",
            asr = "Asr",
            maghrib = "Maghrib",
            isha = "Isha",
            todayPrayers = "Horarios de oración de hoy",
            hijriDate = "Fecha Hijri",
            gregorianDate = "Fecha Gregoriana",
            location = "Ubicación actual",
            changeLocation = "Cambiar ciudad",
            autoGps = "GPS Automático",
            searchingLocation = "Buscando ubicación...",
            permissionRequired = "Permiso de ubicación requerido",
            grantGps = "Activar GPS",
            manualCity = "Seleccionar ciudad",
            prayerAlertMode = "Modo de alerta",
            fullAthan = "Adhan completo",
            takbeerOnly = "Solo Takbeer",
            tone = "Tono suave",
            silent = "Silencio",
            playAthanTest = "Probar Adhan",
            stopAthan = "Detener Adhan",
            qiblaTitle = "Brújula Qibla",
            pointToKaaba = "Apunta tu teléfono hacia la Kaaba",
            qiblaAligned = "Estás orientado a la Qibla",
            degreesFromNorth = "Grados desde el Norte",
            distanceToKaaba = "Distancia a La Meca",
            calibrateCompass = "Calibra moviendo el teléfono en forma de 8",
            compassHint = "Mantén el teléfono plano para mayor precisión",
            quranTitle = "Sagrado Corán",
            searchSurah = "Buscar sura o aleya...",
            surahs = "Suras",
            juz = "Juz",
            bookmarks = "Marcadores",
            versesCount = "aleyas",
            meccan = "Mequí",
            medinan = "Medinés",
            fontSize = "Tamaño de fuente",
            reciter = "Recitador",
            nowPlaying = "Reproduciendo ahora",
            playAllSurah = "Reproducir Sura",
            pauseAudio = "Pausar",
            resumeAudio = "Reanudar",
            nextAyah = "Siguiente Aleya",
            prevAyah = "Aleya Anterior",
            bismillah = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
            noBookmarks = "Sin aleyas guardadas",
            bookmarkAdded = "Aleya guardada",
            bookmarkRemoved = "Aleya eliminada",
            azkarTitle = "Súplicas & Tasbih",
            morningAzkar = "Azkar de la Mañana",
            eveningAzkar = "Azkar de la Tarde",
            postPrayerAzkar = "Tras la Oración",
            sleepAzkar = "Antes de Dormir",
            tasbeehCounter = "Tasbih Digital",
            resetCounter = "Reiniciar",
            target = "Objetivo",
            totalDone = "Total",
            tapToCount = "Toca la pantalla para contar",
            subhanallah = "Subhanallah",
            alhamdulillah = "Alhamdulillah",
            allahuAkbar = "Allahu Akbar",
            lailahaillallah = "La ilaha illa Allah",
            astaghfirullah = "Astaghfirullah",
            settingsTitle = "Configuración",
            language = "Idioma",
            selectLanguage = "Seleccionar idioma",
            calculationMethod = "Método de cálculo",
            muezzinVoice = "Voz del Muecín",
            notifications = "Notificaciones de Adhan",
            notificationsDesc = "Alertas al inicio de cada rezo",
            darkMode = "Modo Oscuro",
            followSystem = "Seguir sistema",
            aboutApp = "Acerca de Noor Al-Iman",
            version = "Versión 1.0"
        )
        AppLanguage.TURKISH -> AppStrings(
            appName = "Noor Al-Iman",
            navHome = "Namaz",
            navQuran = "Kuran",
            navQibla = "Kıble",
            navAzkar = "Zikirler",
            navSettings = "Ayarlar",
            nextPrayer = "Sıradaki Vakit",
            remainingTime = "Kalan Süre",
            fajr = "İmsak / Sabah",
            sunrise = "Güneş",
            dhuhr = "Öğle",
            asr = "İkindi",
            maghrib = "Akşam",
            isha = "Yatsı",
            todayPrayers = "Günün Namaz Vakitleri",
            hijriDate = "Hicri Tarih",
            gregorianDate = "Miladi Tarih",
            location = "Mevcut Konum",
            changeLocation = "Şehir Değiştir",
            autoGps = "Otomatik GPS",
            searchingLocation = "Konum bulunuyor...",
            permissionRequired = "Konum izni gereklidir",
            grantGps = "Konumu Aç",
            manualCity = "Şehir Seç",
            prayerAlertMode = "Ezan Bildirim Modu",
            fullAthan = "Tam Ezan",
            takbeerOnly = "Sadece Tekbir",
            tone = "Hafif Ses",
            silent = "Sessiz",
            playAthanTest = "Ezanı Dinle",
            stopAthan = "Ezanı Durdur",
            qiblaTitle = "Kıble Pusulası",
            pointToKaaba = "Telefonunuzu Kabe'ye doğru çevirin",
            qiblaAligned = "Şu anda Kıble yönündesiniz",
            degreesFromNorth = "Kuzeyden Derece",
            distanceToKaaba = "Mekke'ye Mesafe",
            calibrateCompass = "Kalibrasyon için telefonu 8 şeklinde sallayın",
            compassHint = "En doğru sonuç için telefonu düz tutun",
            quranTitle = "Kuran-ı Kerim",
            searchSurah = "Sure veya ayet ara...",
            surahs = "Sureler",
            juz = "Cüzler",
            bookmarks = "Kayıtlılar",
            versesCount = "ayet",
            meccan = "Mekki",
            medinan = "Medeni",
            fontSize = "Yazı Boyutu",
            reciter = "Hafız / Kari",
            nowPlaying = "Çalınıyor",
            playAllSurah = "Sureyi Dinle",
            pauseAudio = "Duraklat",
            resumeAudio = "Devam Et",
            nextAyah = "Sonraki Ayet",
            prevAyah = "Önceki Ayet",
            bismillah = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
            noBookmarks = "Kayıtlı ayet bulunamadı",
            bookmarkAdded = "Ayet kaydedildi",
            bookmarkRemoved = "Ayet silindi",
            azkarTitle = "Dualar & Zikirmatik",
            morningAzkar = "Sabah Duaları",
            eveningAzkar = "Akşam Duaları",
            postPrayerAzkar = "Namaz Sonrası Dualar",
            sleepAzkar = "Uyku Öncesi Dualar",
            tasbeehCounter = "Dijital Zikirmatik",
            resetCounter = "Sıfırla",
            target = "Hedef",
            totalDone = "Toplam Zikir",
            tapToCount = "Saymak için ekrana dokunun",
            subhanallah = "Sübhanallah",
            alhamdulillah = "Elhamdülillah",
            allahuAkbar = "Allahu Ekber",
            lailahaillallah = "La ilahe illallah",
            astaghfirullah = "Estağfurullah",
            settingsTitle = "Genel Ayarlar",
            language = "Uygulama Dili",
            selectLanguage = "Dil Seçin",
            calculationMethod = "Hesaplama Yöntemi",
            muezzinVoice = "Müezzin Sesi",
            notifications = "Ezan Bildirimleri",
            notificationsDesc = "Her vakitte sesli hatırlatma",
            darkMode = "Karanlık Mod",
            followSystem = "Sistem Varsayılanı",
            aboutApp = "Noor Al-Iman Hakkında",
            version = "Sürüm 1.0"
        )
        AppLanguage.INDONESIAN -> AppStrings(
            appName = "Noor Al-Iman",
            navHome = "Sholat",
            navQuran = "Al-Qur'an",
            navQibla = "Kiblat",
            navAzkar = "Dzikir",
            navSettings = "Pengaturan",
            nextPrayer = "Waktu Sholat Berikutnya",
            remainingTime = "Sisa Waktu",
            fajr = "Subuh",
            sunrise = "Terbit",
            dhuhr = "Dzuhur",
            asr = "Ashar",
            maghrib = "Maghrib",
            isha = "Isya",
            todayPrayers = "Jadwal Sholat Hari Ini",
            hijriDate = "Tanggal Hijriyah",
            gregorianDate = "Tanggal Masehi",
            location = "Lokasi Saat Ini",
            changeLocation = "Ubah Kota",
            autoGps = "GPS Otomatis",
            searchingLocation = "Mencari lokasi...",
            permissionRequired = "Izin lokasi diperlukan",
            grantGps = "Aktifkan GPS",
            manualCity = "Pilih Kota",
            prayerAlertMode = "Mode Suara Adzan",
            fullAthan = "Adzan Penuh",
            takbeerOnly = "Hanya Takbir",
            tone = "Nada Lembut",
            silent = "Senyap",
            playAthanTest = "Coba Adzan",
            stopAthan = "Hentikan Adzan",
            qiblaTitle = "Kompas Kiblat",
            pointToKaaba = "Arahkan ponsel Anda ke Ka'bah",
            qiblaAligned = "Anda tepat menghadap Kiblat",
            degreesFromNorth = "Derajat dari Utara",
            distanceToKaaba = "Jarak ke Makkah",
            calibrateCompass = "Gerakkan ponsel membentuk angka 8 untuk kalibrasi",
            compassHint = "Pegang ponsel mendatar untuk hasil akurat",
            quranTitle = "Al-Qur'an Al-Karim",
            searchSurah = "Cari surah atau ayat...",
            surahs = "Surah",
            juz = "Juz",
            bookmarks = "Tersimpan",
            versesCount = "ayat",
            meccan = "Makkiyah",
            medinan = "Madaniyah",
            fontSize = "Ukuran Tulisan",
            reciter = "Qari",
            nowPlaying = "Sedang Diputar",
            playAllSurah = "Putar Surah",
            pauseAudio = "Jeda",
            resumeAudio = "Lanjutkan",
            nextAyah = "Ayat Selanjutnya",
            prevAyah = "Ayat Sebelumnya",
            bismillah = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
            noBookmarks = "Belum ada ayat disimpan",
            bookmarkAdded = "Ayat disimpan",
            bookmarkRemoved = "Ayat dihapus dari simpanan",
            azkarTitle = "Dzikir & Tasbih",
            morningAzkar = "Dzikir Pagi",
            eveningAzkar = "Dzikir Petang",
            postPrayerAzkar = "Dzikir Setelah Sholat",
            sleepAzkar = "Dzikir Sebelum Tidur",
            tasbeehCounter = "Tasbih Digital",
            resetCounter = "Reset",
            target = "Target",
            totalDone = "Total Dzikir",
            tapToCount = "Ketuk layar untuk menghitung",
            subhanallah = "Subhanallah",
            alhamdulillah = "Alhamdulillah",
            allahuAkbar = "Allahu Akbar",
            lailahaillallah = "Laa ilaaha illallah",
            astaghfirullah = "Astaghfirullah",
            settingsTitle = "Pengaturan",
            language = "Bahasa Aplikasi",
            selectLanguage = "Pilih Bahasa",
            calculationMethod = "Metode Perhitungan",
            muezzinVoice = "Suara Muadzin",
            notifications = "Notifikasi Adzan",
            notificationsDesc = "Pengingat sholat tepat waktu",
            darkMode = "Mode Gelap",
            followSystem = "Ikuti Sistem",
            aboutApp = "Tentang Noor Al-Iman",
            version = "Versi 1.0"
        )
        AppLanguage.PORTUGUESE -> AppStrings(
            appName = "Noor Al-Iman",
            navHome = "Orações",
            navQuran = "Alcorão",
            navQibla = "Qibla",
            navAzkar = "Azkar",
            navSettings = "Definições",
            nextPrayer = "Próxima Oração",
            remainingTime = "Tempo Restante",
            fajr = "Fajr",
            sunrise = "Nascer do Sol",
            dhuhr = "Dhuhr",
            asr = "Asr",
            maghrib = "Maghrib",
            isha = "Isha",
            todayPrayers = "Horários de Oração de Hoje",
            hijriDate = "Data Islâmica",
            gregorianDate = "Data Gregoriana",
            location = "Localização Atual",
            changeLocation = "Mudar Cidade",
            autoGps = "GPS Automático",
            searchingLocation = "A procurar localização...",
            permissionRequired = "Permissão de localização necessária",
            grantGps = "Ativar GPS",
            manualCity = "Escolher Cidade",
            prayerAlertMode = "Modo de Alerta",
            fullAthan = "Adhan Completo",
            takbeerOnly = "Apenas Takbeer",
            tone = "Tom Suave",
            silent = "Silencioso",
            playAthanTest = "Ouvir Adhan",
            stopAthan = "Parar Adhan",
            qiblaTitle = "Bússola Qibla",
            pointToKaaba = "Aponte o telefone para a Caaba",
            qiblaAligned = "Está voltado para a Qibla",
            degreesFromNorth = "Graus do Norte",
            distanceToKaaba = "Distância até Meca",
            calibrateCompass = "Calibre movendo em forma de 8",
            compassHint = "Mantenha o telefone nivelado",
            quranTitle = "Alcorão Sagrado",
            searchSurah = "Pesquisar surata ou versículo...",
            surahs = "Suratas",
            juz = "Juz",
            bookmarks = "Guardados",
            versesCount = "versículos",
            meccan = "Mequense",
            medinan = "Medinense",
            fontSize = "Tamanho do Texto",
            reciter = "Recitador",
            nowPlaying = "A Tocar",
            playAllSurah = "Tocar Surata",
            pauseAudio = "Pausar",
            resumeAudio = "Retomar",
            nextAyah = "Próximo Versículo",
            prevAyah = "Versículo Anterior",
            bismillah = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
            noBookmarks = "Nenhum versículo guardado",
            bookmarkAdded = "Versículo guardado",
            bookmarkRemoved = "Versículo removido",
            azkarTitle = "Súplicas & Tasbih",
            morningAzkar = "Súplicas da Manhã",
            eveningAzkar = "Súplicas da Tarde",
            postPrayerAzkar = "Após a Oração",
            sleepAzkar = "Antes de Dormir",
            tasbeehCounter = "Tasbih Digital",
            resetCounter = "Repor",
            target = "Meta",
            totalDone = "Total",
            tapToCount = "Toque no ecrã para contar",
            subhanallah = "Subhanallah",
            alhamdulillah = "Alhamdulillah",
            allahuAkbar = "Allahu Akbar",
            lailahaillallah = "La ilaha illa Allah",
            astaghfirullah = "Astaghfirullah",
            settingsTitle = "Definições",
            language = "Idioma",
            selectLanguage = "Escolher Idioma",
            calculationMethod = "Método de Cálculo",
            muezzinVoice = "Voz do Muezzin",
            notifications = "Notificações do Adhan",
            notificationsDesc = "Alertas a cada oração",
            darkMode = "Modo Escuro",
            followSystem = "Seguir Sistema",
            aboutApp = "Sobre Noor Al-Iman",
            version = "Versão 1.0"
        )
        AppLanguage.ITALIAN -> AppStrings(
            appName = "Noor Al-Iman",
            navHome = "Preghiere",
            navQuran = "Corano",
            navQibla = "Qibla",
            navAzkar = "Azkar",
            navSettings = "Impostazioni",
            nextPrayer = "Prossima Preghiera",
            remainingTime = "Tempo Rimanente",
            fajr = "Fajr",
            sunrise = "Alba",
            dhuhr = "Dhuhr",
            asr = "Asr",
            maghrib = "Maghrib",
            isha = "Isha",
            todayPrayers = "Orari delle Preghiere di Oggi",
            hijriDate = "Data Egira",
            gregorianDate = "Data Gregoriana",
            location = "Posizione Attuale",
            changeLocation = "Cambia Città",
            autoGps = "GPS Automatico",
            searchingLocation = "Ricerca posizione...",
            permissionRequired = "Permesso di posizione richiesto",
            grantGps = "Attiva GPS",
            manualCity = "Scegli Città",
            prayerAlertMode = "Modalità Allarme",
            fullAthan = "Adhan Completo",
            takbeerOnly = "Solo Takbeer",
            tone = "Tono Leggero",
            silent = "Silenzioso",
            playAthanTest = "Prova Adhan",
            stopAthan = "Ferma Adhan",
            qiblaTitle = "Bussola Qibla",
            pointToKaaba = "Punta il telefono verso la Kaaba",
            qiblaAligned = "Sei orientato verso la Qibla",
            degreesFromNorth = "Gradi dal Nord",
            distanceToKaaba = "Distanza dalla Mecca",
            calibrateCompass = "Calibra muovendo a forma di 8",
            compassHint = "Tieni il telefono in piano",
            quranTitle = "Sacro Corano",
            searchSurah = "Cerca sura o versetto...",
            surahs = "Sure",
            juz = "Juz",
            bookmarks = "Salvati",
            versesCount = "versetti",
            meccan = "Meccana",
            medinan = "Medinese",
            fontSize = "Dimensione Carattere",
            reciter = "Recitatore",
            nowPlaying = "In Riproduzione",
            playAllSurah = "Riproduci Sura",
            pauseAudio = "Pausa",
            resumeAudio = "Riprendi",
            nextAyah = "Versetto Successivo",
            prevAyah = "Versetto Precedente",
            bismillah = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
            noBookmarks = "Nessun versetto salvato",
            bookmarkAdded = "Versetto salvato",
            bookmarkRemoved = "Versetto rimosso",
            azkarTitle = "Suppliche & Tasbih",
            morningAzkar = "Suppliche del Mattino",
            eveningAzkar = "Suppliche della Sera",
            postPrayerAzkar = "Dopo la Preghiera",
            sleepAzkar = "Prima di Dormire",
            tasbeehCounter = "Tasbih Digitale",
            resetCounter = "Reimposta",
            target = "Obiettivo",
            totalDone = "Totale",
            tapToCount = "Tocca lo schermo per contare",
            subhanallah = "Subhanallah",
            alhamdulillah = "Alhamdulillah",
            allahuAkbar = "Allahu Akbar",
            lailahaillallah = "La ilaha illa Allah",
            astaghfirullah = "Astaghfirullah",
            settingsTitle = "Impostazioni",
            language = "Lingua Applicazione",
            selectLanguage = "Seleziona Lingua",
            calculationMethod = "Metodo di Calcolo",
            muezzinVoice = "Voce del Muezzin",
            notifications = "Notifiche Adhan",
            notificationsDesc = "Avvisi puntuali per ogni preghiera",
            darkMode = "Modalità Scura",
            followSystem = "Segui Sistema",
            aboutApp = "Info su Noor Al-Iman",
            version = "Versione 1.0"
        )
        AppLanguage.ENGLISH -> AppStrings(
            appName = "Noor Al-Iman",
            navHome = "Prayer",
            navQuran = "Quran",
            navQibla = "Qibla",
            navAzkar = "Azkar & Tasbeeh",
            navSettings = "Settings",
            nextPrayer = "Next Prayer",
            remainingTime = "Remaining",
            fajr = "Fajr",
            sunrise = "Sunrise",
            dhuhr = "Dhuhr",
            asr = "Asr",
            maghrib = "Maghrib",
            isha = "Isha",
            todayPrayers = "Today's Prayer Schedule",
            hijriDate = "Hijri Date",
            gregorianDate = "Gregorian Date",
            location = "Current Location",
            changeLocation = "Change City",
            autoGps = "Auto GPS Detection",
            searchingLocation = "Locating...",
            permissionRequired = "Location permission needed for accurate prayers and Qibla",
            grantGps = "Enable Location",
            manualCity = "Select City Manually",
            prayerAlertMode = "Prayer Alert Sound",
            fullAthan = "Full Athan",
            takbeerOnly = "Takbeer Only",
            tone = "Gentle Tone",
            silent = "Silent",
            playAthanTest = "Test Athan",
            stopAthan = "Stop Athan",
            qiblaTitle = "Qibla Compass",
            pointToKaaba = "Point your device towards the Kaaba",
            qiblaAligned = "You are facing the Qibla directly",
            degreesFromNorth = "Degrees from North",
            distanceToKaaba = "Distance to Makkah",
            calibrateCompass = "Wave device in a figure-8 to calibrate",
            compassHint = "Hold device flat for maximum precision",
            quranTitle = "The Holy Quran",
            searchSurah = "Search surah or ayah...",
            surahs = "Surahs",
            juz = "Juzs",
            bookmarks = "Bookmarks",
            versesCount = "verses",
            meccan = "Meccan",
            medinan = "Medinan",
            fontSize = "Font Size",
            reciter = "Reciter",
            nowPlaying = "Now Playing",
            playAllSurah = "Play Surah",
            pauseAudio = "Pause",
            resumeAudio = "Resume",
            nextAyah = "Next Ayah",
            prevAyah = "Previous Ayah",
            bismillah = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
            noBookmarks = "No bookmarks yet",
            bookmarkAdded = "Ayah bookmarked",
            bookmarkRemoved = "Bookmark removed",
            azkarTitle = "Azkar & Digital Tasbeeh",
            morningAzkar = "Morning Azkar",
            eveningAzkar = "Evening Azkar",
            postPrayerAzkar = "Post-Prayer Azkar",
            sleepAzkar = "Bedtime Azkar",
            tasbeehCounter = "Digital Tasbeeh",
            resetCounter = "Reset Counter",
            target = "Target",
            totalDone = "Total Count",
            tapToCount = "Tap anywhere to count",
            subhanallah = "SubhanAllah (Glory be to Allah)",
            alhamdulillah = "Alhamdulillah (Praise be to Allah)",
            allahuAkbar = "Allahu Akbar (Allah is Greatest)",
            lailahaillallah = "La Ilaha Illa Allah",
            astaghfirullah = "Astaghfirullah (I seek forgiveness)",
            settingsTitle = "Settings",
            language = "App Language",
            selectLanguage = "Select Language",
            calculationMethod = "Prayer Calculation Method",
            muezzinVoice = "Muezzin Voice",
            notifications = "Athan Notifications",
            notificationsDesc = "Timely alerts for each prayer",
            darkMode = "Dark Mode",
            followSystem = "Follow System",
            aboutApp = "About Noor Al-Iman",
            version = "Version 1.0"
        )
    }
}
